version: '3'
services:
  mongo:
    image: mongo
    container_name: boma-mongo
    ports:
      - "27017:27017"
  backend:
    build: .
    container_name: boma-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
