import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/MainLayout";
import ClientSideWrapper from "@/components/ClientSideWrapper"; // Client logic here

export const metadata: Metadata = {
  title: "Next Js Tailwind Sandbox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientSideWrapper>{children}</ClientSideWrapper>
      </body>
    </html>
  );
}
